micronaut:
  server:
    port: 8200

r2dbc:
  datasources:
    default:
      url: r2dbc:proxy:pool:postgresql://localhost:5432/postgres
      username: saas
      password: admin1234!
      driver: proxy
      protocol: postgresql
      dialect: postgres
      options:
        maxSize: 20
        initialSize : 10
        validationQuery : "SELECT 1"


