### GET request to example server
GET http://localhost:8200/projects/list?size=2

### POST request to example server
POST http://localhost:8200/projects

poject2

### POST request to example server
POST http://localhost:8200/projects/ex

pojectsdfsdf-sdfsdf

### DELETE request to example server
DELETE http://localhost:8200/projects/9


### PUT request to example server
PUT http://localhost:8200/projects
Content-Type: application/json

{
    "id" : 4,
    "name" : "update name2222"
}


### GET id
GET http://localhost:8200/projects/5



