### GET request to example server
GET http://localhost:8200/persons

### POST request to example server
POST http://localhost:8200/persons
Content-Type: application/json

{
  "name": "hoon",
  "age": 23
}

### DELETE request to example server
DELETE http://localhost:8200/persons/1


### GET id
GET http://localhost:8200/persons/2



