micronaut:
  server:
    port: 9100


kafka:
  bootstrap:
    servers:
      - localhost:9091
      - localhost:9092
      - localhost:9093
  consumers:
    default:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  producers:
    default:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

elasticsearch:
  http-hosts: http://localhost:9200



org-id: ${ORG_ID}
instance-id: ${INSTANCE_ID}

topic:
  consumer: tracking.organization.${ORG_ID}
  producer : tracking.organization.${ORG_ID}.test
